/**
 * 플랫폼 + 브랜드 마스터 리스트 (사용자 제공 엑셀 기준).
 *
 * 사용처:
 *   - CaseEditor: 플랫폼 / 브랜드 입력 시 datalist 자동완성 후보
 *   - CasesTab: 필터 드롭다운 후보
 *
 * 주의:
 *   - 두 필드 모두 **자유 입력 허용** (마스터에 없는 신규 값도 사용자가 직접 입력 가능)
 *   - 추가/삭제는 이 파일을 직접 수정해서 PR. 신규 케이스 작성 시 자동완성에 반영됨
 *   - DB schema 측면: cases.platform 의 CHECK 제약은 migration 014 에서 제거됨
 */

export const PLATFORM_LIST = [
  "106house",
  "11st",
  "1688",
  "29CM",
  "4910",
  "ABLY",
  "AKmall",
  "Alibaba",
  "Aliexpress-AE",
  "Aliexpress-AU",
  "Aliexpress-BE",
  "Aliexpress-BR",
  "Aliexpress-CA",
  "Aliexpress-CL",
  "Aliexpress-CN",
  "Aliexpress-CZ",
  "Aliexpress-DE",
  "Aliexpress-DK",
  "Aliexpress-ES",
  "Aliexpress-FI",
  "Aliexpress-FR",
  "Aliexpress-GB",
  "Aliexpress-ID",
  "Aliexpress-IL",
  "Aliexpress-IT",
  "Aliexpress-JP",
  "Aliexpress-KR",
  "Aliexpress-MX",
  "Aliexpress-MY",
  "Aliexpress-NL",
  "Aliexpress-NO",
  "Aliexpress-PH",
  "Aliexpress-PL",
  "Aliexpress-RU",
  "Aliexpress-SA",
  "Aliexpress-SE",
  "Aliexpress-SG",
  "Aliexpress-TH",
  "Aliexpress-TR",
  "Aliexpress-TW",
  "Aliexpress-US",
  "Aliexpress-VN",
  "Amazon-AU",
  "Amazon-CA",
  "Amazon-CN",
  "Amazon-FR",
  "Amazon-US",
  "Auction",
  "BALAAN",
  "bonanza",
  "Bunjang",
  "BUYMA",
  "Carousell",
  "CJmall",
  "Coupang",
  "DHgate",
  "Douyin Mall",
  "eBay",
  "eBay - ES",
  "eBay - FR",
  "eBay - IT",
  "eBay - UK",
  "eBay-CA",
  "eBay-CH",
  "eBay-EU",
  "eBay-HK",
  "eBay-SG",
  "eBay-US",
  "eBay.ca - cafr",
  "EIT",
  "ELAND MALL",
  "Etsy",
  "Facebook",
  "Facebook-BR",
  "Facebook-Marketplace-CO",
  "Facebook-Marketplace-CR",
  "Facebook-Marketplace-DR",
  "Facebook-Marketplace-GT",
  "Facebook-Marketplace-PA",
  "Feelway",
  "FreeShip",
  "G9",
  "Galleria",
  "Gmarket",
  "GSShop",
  "halfclub",
  "HC360",
  "HelloMarket",
  "HIVER",
  "Hmall",
  "Hyundaihmall",
  "IFmall",
  "Instagram",
  "Interpark",
  "Jingdong",
  "KakaoGift",
  "KakaoStory",
  "KakaotalkChannel",
  "KakaotalkStore",
  "KREAM",
  "Lazada-ID",
  "Lazada-MY",
  "Lazada-PH",
  "Lazada-SG",
  "Lazada-TH",
  "Lazada-VN",
  "LF square",
  "LFmall",
  "LotteiMall",
  "LotteON",
  "MarketYandex",
  "Melchi",
  "Mercadolibre-AR",
  "Mercadolibre-CL",
  "Mercadolibre-CO",
  "Mercadolibre-CR",
  "Mercadolibre-EC",
  "Mercadolibre-MX",
  "Mercadolibre-PA",
  "Mercadolibre-PE",
  "Mercadolibre-VE",
  "Mercadolivre-BR",
  "mercari",
  "momo",
  "MUSINSA",
  "MustIT",
  "NaverBand",
  "NaverBlog",
  "NaverCafe",
  "NaverShopping",
  "NHMarket",
  "oco",
  "Qoo10",
  "Qoo10-JP",
  "Rakuten",
  "Shein-US",
  "Shopee-BR",
  "Shopee-CL",
  "Shopee-CO",
  "Shopee-ES",
  "Shopee-FR",
  "Shopee-ID",
  "Shopee-MX",
  "Shopee-MY",
  "Shopee-PH",
  "Shopee-PL",
  "Shopee-SG",
  "Shopee-TH",
  "Shopee-TW",
  "Shopee-VN",
  "ShoppingHow",
  "shoppy",
  "SINSEGAE",
  "SIVILLAGE",
  "SKStoa",
  "SmartStore",
  "SSF SHOP",
  "SSG",
  "Stand-Alone",
  "Stand-Alone (RU)",
  "Taobao",
  "Taobao-HK",
  "TEMU",
  "tenbyten",
  "Thehyundai",
  "TikTok",
  "TikTok Shop",
  "Tmall",
  "TMON",
  "Trenbe",
  "Twitter",
  "UNIT808",
  "W.CONCEPT",
  "Walmart",
  "WeMakePrice",
  "Wizwid",
  "Xiaohongshu",
  "Youtube",
  "당근마켓",
  "이마트몰",
  "홈&쇼핑",
  "확인 불가",
];

export const BRAND_LIST = [
  "(주)런컬렉션",
  "(주)바이트랩",
  "(주)쏠리드",
  "(주)파인드폼",
  "(주)포켓몬코리아",
  "3M Company",
  "8SECONDS",
  "Aardman Animations Limited",
  "acne studio",
  "ACQUA DI PARMA",
  "Acushnet Korea",
  "Adidas",
  "Adobe",
  "Alaïa",
  "Alexander McQueen",
  "Alibaba",
  "ALIITA S.r.l.",
  "ALTRA LLC",
  "Ami",
  "Apple Inc.",
  "Armani",
  "ASICS",
  "ASOS",
  "Audemars Piguet",
  "Audi",
  "Balenciaga",
  "BAOBAO",
  "BASIC HOUSE",
  "Bath & Body Work",
  "Beam Suntory",
  "BEANPOLE",
  "BISSELL",
  "BMW",
  "Bobbi Brown",
  "BOSE",
  "Bottega Veneta",
  "Brita",
  "BROOKS SPORTS",
  "bulgari",
  "Burberry Limited",
  "BYREDO",
  "Calvin Klein",
  "CANADA GOOSE",
  "Canon",
  "Cartier",
  "CASETiFY",
  "Casio",
  "Celine_Mystery Shopper Program",
  "Chanel",
  "chloe",
  "Coach",
  "COLLUSION",
  "COMME des GARCONS",
  "CONVERSE",
  "cosrx",
  "Coupang",
  "COURONNE",
  "COVERNAT",
  "Crocs Inc.",
  "CUSTOMELLOW",
  "Daiso",
  "DAIWA",
  "DC Comics",
  "Deckers Outdoor Corporation",
  "Dior",
  "Diptyque",
  "Discovery",
  "Dr. Martens Korea",
  "Dreams Inc.",
  "Dyson",
  "emis",
  "EPSON",
  "Ermenegildo Zegna",
  "Essity",
  "ESTEE LAUDER",
  "Etc",
  "Fallett",
  "Fitflop",
  "FIVE SPACE CO., LTD",
  "Footjoy",
  "Fossil Group Inc.",
  "FRED PARIS",
  "G-SHOCK",
  "Galaxy",
  "GANNI",
  "Geneva Laboratories Limited (Bio-oil)",
  "Gentle Monster",
  "Golden Goose S.p.A.",
  "GREGORY",
  "Gucci",
  "Harman",
  "HD 한국조선해양",
  "Hennes & Mauritz",
  "HOKA",
  "HUAWEI TECHNOLOGIES CO., LTD.",
  "Hyundai Mobis Co., Ltd.",
  "Icebreaker Apparel, LLC",
  "Incopro",
  "IPX Corporation & HYBE Corp.",
  "IRO",
  "JACQUEMUS",
  "JanSport Apparel Corp.",
  "JBL",
  "Jellycat Ltd",
  "Jo Malone London",
  "JT International",
  "Jucy Judy",
  "JUUN.J",
  "Kakao Corporation",
  "Kangol",
  "Kenzo",
  "Kering",
  "Kiehl's",
  "Kipling Apparel Corp.",
  "KUHO",
  "kuho plus",
  "LACOSTE",
  "Lamborghini",
  "LAURASTAR",
  "LEBEIGE",
  "LEE",
  "Lego",
  "LEGO",
  "Lindberg A/S",
  "Logitech",
  "Longchamp",
  "Louis Vuitton",
  "Lowepro",
  "LUCKY CHOUETTE",
  "MAISON KITSUNE",
  "Malbon Golf",
  "Marc Jacobs - Coupang",
  "MARDI MERCREDI",
  "MARGIELA",
  "Marni Group S.R.L.",
  "Marshall Amplification Plc",
  "Mattel Inc.",
  "Mercis BV (Miffy)",
  "Michael Kors",
  "MIND BRIDGE",
  "MISS SELFRIDGE",
  "MISTO KOREA LTD. (FILA Korea Co., Ltd.)",
  "MLB",
  "Moncler",
  "Montblanc",
  "MOOSE KNUCKLES",
  "move free",
  "Myriad",
  "Myriad (Brand Manager)",
  "Myriadiplaw",
  "National Geographic",
  "NAVER",
  "New Balance",
  "NIKE",
  "Nintendo Co., Ltd.",
  "NXP",
  "OFF-WHITE",
  "OLAPLEX, INC.",
  "On Clouds GmbH",
  "Onitsuka Tiger",
  "Ostrichpillow",
  "Otterbox",
  "Pandora A/S",
  "Patagonia",
  "Paula's choice",
  "PharmaResearch",
  "Philips",
  "PITTA MASK",
  "Pokemon",
  "Pomellato",
  "POPMART",
  "Porsche",
  "PUMA",
  "PXG",
  "RALPHLAUREN",
  "ReFa",
  "Rogatis",
  "Saint Laurent",
  "Salvatore Ferragamo",
  "Samsonite",
  "Samsung C&T Fashion Group",
  "Schaeffler Technologies AG & Co. KG",
  "Sennheiser",
  "Shenzhen Uwell Technology Co., Ltd.",
  "SK2",
  "SPIGEN",
  "starbucks",
  "Stone Island",
  "STUDIO BANANA SL",
  "Stussy",
  "Supreme",
  "Swarovski",
  "Tangle Teezer",
  "Taylor Made",
  "TBL Licensing LLC",
  "The North Face Apparel Corp.",
  "theKARY",
  "Theory",
  "THOM BROWNE",
  "TIFFANY&Co.",
  "TOM FORD",
  "Tommy Hilfiger",
  "TOPMAN",
  "TOPSHOP",
  "TORY BURCH",
  "ToryBurch",
  "TUMI",
  "UFI Filters",
  "Under Armour",
  "Uniform Bridge",
  "UNIQLO",
  "Van Cleef & Arpels",
  "VANS",
  "Versace",
  "Versuni Holding B.V.",
  "Victoria's Secret",
  "vivienne westwood",
  "W-D Apparel Company, LLC (Dickies)",
  "Wacky WiLLy",
  "Wallace and Gromit",
  "Warner Bros. Entertainment Inc.",
  "WD",
  "Wella",
  "Western Digital",
  "Xiaomi",
  "Zenith",
  "그랜즈레미디",
  "나우푸드",
  "나이키",
  "노르딕",
  "노스페이스",
  "대한항공",
  "대현인사이드",
  "라네즈",
  "로이비쥬얼",
  "르무통",
  "머슬팜",
  "미샤",
  "바이오오일 - Coupang",
  "베이프",
  "뼈엔",
  "산타마리아노벨라",
  "삼성전자",
  "샌디스크",
  "샤넬",
  "설화수",
  "스킨1004",
  "스킨천사",
  "쏜",
  "아디다스",
  "아모레퍼시픽",
  "아모스",
  "아이오페",
  "아쿠아디파르마",
  "알리바바",
  "암웨이",
  "애플",
  "에뛰드",
  "에스트라",
  "에스티로더",
  "엔젤",
  "우포스",
  "이니스프리 - Coupang",
  "일리윤",
  "주식회사 블루엘리펀트",
  "주식회사 앱솔브랩",
  "질레트",
  "캘빈클라인",
  "컨버스",
  "코닥",
  "코오롱인더스트리 주식회사",
  "쿠팡",
  "크록스",
  "키엘",
  "트래센드",
  "파인뷰",
  "피지오겔",
  "한국일보",
  "헤라",
  "헤라 옴므",
  "현대자동차",
];
